name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  REPO_NAME: algo-trading-bot

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: App Settings Variable Substitution
      uses: microsoft/variable-substitution@v1
      with:
        files: './src/Trading.Bot/appsettings.json'
      env:
        Constants.ApiKey: ${{ secrets.OANDAAPIKEY }}
        Constants.AccountId: ${{ secrets.OANDAACCOUNTID }}
        EmailConfiguration.Password: ${{ secrets.EMAILPASSWORD }}

    - name: Build and Push Docker Image
      uses: mr-smithers-excellent/docker-build-push@v6
      with:
        image: ${{ secrets.DOCKER_USER }}/${{ env.REPO_NAME }}
        tags: latest
        registry: docker.io
        dockerfile: ./src/Trading.Bot/Dockerfile
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASSWORD }}
