name: Publish .NET App

on:
  workflow_dispatch:
  push:
    branches:
    - main

env:
  AZURE_WEBAPP_NAME: forex-trading-bot
  AZURE_WEBAPP_PACKAGE_PATH: "./publish"

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: App Settings Variable Substitution
        uses: microsoft/variable-substitution@v1
        with:
          files: './src/Trading.Bot/appsettings.json'
        env:
          Constants.ApiKey: ${{ secrets.OANDAAPIKEY }}
          Constants.AccountId: ${{ secrets.OANDAACCOUNTID }}
          EmailConfiguration.Password: ${{ secrets.EMAILPASSWORD }}
          
      - name: Restore
        run: dotnet restore ./src/Trading.Bot/Trading.Bot.csproj
        
      - name: Build
        run: dotnet build ./src/Trading.Bot/Trading.Bot.csproj --configuration Release --no-restore
        
      - name: Publish
        run: dotnet publish ./src/Trading.Bot/Trading.Bot.csproj --configuration Release --no-build --output '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}'

      - name: Deploy to Azure
        uses: azure/webapps-deploy@v4
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
          package: "${{ env.AZURE_WEBAPP_PACKAGE_PATH }}"
