name: Publish .NET App

on:
  workflow_dispatch:
  push:
    branches:
    - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x
          
      - name: Restore
        run: dotnet restore ./src/Trading.Bot/Trading.Bot.csproj
        
      - name: Build
        run: dotnet build ./src/Trading.Bot/Trading.Bot.csproj --configuration Release --no-restore
        
      - name: Publish
        run: dotnet publish ./src/Trading.Bot/Trading.Bot.csproj --configuration Release --no-build
